// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxU3v45Gu1L89vBIMMsmfAujnK_3MQqt8',
    appId: '1:776471273907:web:bb868bcbafcc6899a66bc6',
    messagingSenderId: '776471273907',
    projectId: 'foodapp-4e921',
    authDomain: 'foodapp-4e921.firebaseapp.com',
    storageBucket: 'foodapp-4e921.firebasestorage.app',
    measurementId: 'G-7LD504CNWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC5uynR6ui-27CaXDq7foruEkYEMG48ws',
    appId: '1:776471273907:android:13648dc259325b08a66bc6',
    messagingSenderId: '776471273907',
    projectId: 'foodapp-4e921',
    storageBucket: 'foodapp-4e921.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1438AnCbBzMM_2xNG--5jAExBrvhCj54',
    appId: '1:776471273907:ios:10929428570e3d2da66bc6',
    messagingSenderId: '776471273907',
    projectId: 'foodapp-4e921',
    storageBucket: 'foodapp-4e921.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1438AnCbBzMM_2xNG--5jAExBrvhCj54',
    appId: '1:776471273907:ios:10929428570e3d2da66bc6',
    messagingSenderId: '776471273907',
    projectId: 'foodapp-4e921',
    storageBucket: 'foodapp-4e921.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxU3v45Gu1L89vBIMMsmfAujnK_3MQqt8',
    appId: '1:776471273907:web:86f3665451cb5598a66bc6',
    messagingSenderId: '776471273907',
    projectId: 'foodapp-4e921',
    authDomain: 'foodapp-4e921.firebaseapp.com',
    storageBucket: 'foodapp-4e921.firebasestorage.app',
    measurementId: 'G-5VFYPSGMV0',
  );
}
